
package com.ShopSphere.shop_sphere.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.ShopSphere.shop_sphere.exception.ResourceNotFoundException;
import com.ShopSphere.shop_sphere.model.WishlistItem;
import com.ShopSphere.shop_sphere.repository.WishlistItemDao;
// Optional: verify wishlist exists before adding items
import com.ShopSphere.shop_sphere.repository.WishlistDao;
import com.ShopSphere.shop_sphere.model.Wishlist;

@Service
public class WishlistItemServiceImpl implements WishlistItemService {

    private final WishlistItemDao wishlistItemDao;
    // Optional: include WishlistDao to validate wishlist existence
    private final WishlistDao wishlistDao;

    public WishlistItemServiceImpl(WishlistItemDao wishlistItemDao, WishlistDao wishlistDao) {
        this.wishlistItemDao = wishlistItemDao;
        this.wishlistDao = wishlistDao;
    }

    @Override
    public int addItemToWishlist(WishlistItem wishlistItem) {
        validateWishlistItemForCreate(wishlistItem);

        // Optional: ensure the wishlist exists
        Wishlist wishlist = wishlistDao.findById(wishlistItem.getWishlistId());
        if (wishlist == null) {
            throw new ResourceNotFoundException("Wishlist not found for wishlistId: " + wishlistItem.getWishlistId());
        }

        int id = wishlistItemDao.addItem(wishlistItem);
        if (id <= 0) {
            throw new RuntimeException("Failed to add item to wishlistId=" + wishlistItem.getWishlistId()
                    + " for productId=" + wishlistItem.getProductId());
        }
        return id;
    }

    @Override
    public List<WishlistItem> getItemsByWishlistId(int wishlistId) {
        if (wishlistId <= 0) {
            throw new IllegalArgumentException("wishlistId must be positive");
        }
        List<WishlistItem> items = wishlistItemDao.findByWishlistId(wishlistId);
        // Returning empty list is fine; throw only if strictly required
        return items;
    }

    @Override
    public int deleteItem(int wishlistItemId) {
        if (wishlistItemId <= 0) {
            throw new IllegalArgumentException("wishlistItemId must be positive");
        }
        int rows = wishlistItemDao.deleteItem(wishlistItemId);
        if (rows <= 0) {
            throw new ResourceNotFoundException("No wishlist item found to delete for id: " + wishlistItemId);
        }
        return rows;
    }

    // ---------- Helpers / validations ----------

    private void validateWishlistItemForCreate(WishlistItem wishlistItem) {
        if (wishlistItem == null) {
            throw new IllegalArgumentException("WishlistItem cannot be null");
        }
        if (wishlistItem.getWishlistId() <= 0) {
            throw new IllegalArgumentException("wishlistId must be positive");
        }
        if (wishlistItem.getProductId() <= 0) {
            throw new IllegalArgumentException("productId must be positive");
        }
        // Optional: prevent adding if wishlistItemsId is already set (should be generated by DB)
        if (wishlistItem.getWishlistItemsId() > 0) {
            // Not strictly an error, but typically clients shouldn't set PK before insert
            // You can warn or reset it to 0/ignore, depending on your DAO behavior.
        }
    }
}
